### ISSUE TITLE
main.js has merge conflicts

### ISSUE THREAD

**Issue by knorrium** [mark-hahn/insteon-hub#1]
Hi @mark-hahn 

I found your project while browsing the issues on the home-controller repo and was trying to set it up for my basic use case (a PowerLinc modem connected to the USB port and a dimmer).

It looks like during the last commit, the `main.js` file ended up with merge conflicts on the repo:

https://github.com/mark-hahn/insteon-hub/blob/39028900af35ff14b1cdc85c8a28aef7ce2cb08f/lib/main.js

Can you please commit the clean version?

Thanks!

Felipe

**Comment by mark-hahn** [comment]
Thanks for the notice.  I apparently did not compile it on the last release.  I need to automate that.

It should be fine now.
